#!/usr/bin/env python3
"""Render an N-Queens benchmark JSON into a LaTeX report, then run
pdflatex twice (once for refs, once to settle them) and produce a PDF.

Usage:
    nqueens_bench.py --out results.json
    build_report.py results.json --out report.tex --pdf report.pdf
"""
import argparse
import json
import os
import subprocess
import sys

TEX_TEMPLATE = r"""\documentclass[a4paper,11pt]{article}
\usepackage[margin=22mm]{geometry}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepackage{listings}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue}

\lstset{
  basicstyle=\ttfamily\footnotesize,
  backgroundcolor=\color{black!4},
  frame=single,
  framerule=0pt,
  breaklines=true,
  showstringspaces=false
}

\title{Distributed N-Queens Benchmark \\
  \large Mac + Raspberry Pi 3 (Embedded Xinu, AIPL actor load-balancer)}
\author{Generated by \texttt{tools/build\_report.py}}
\date{__DATE__}

\begin{document}
\maketitle

\begin{abstract}
This report measures wall-clock time for counting all solutions to the
$N$-Queens problem at board sizes __SIZES__, comparing three execution
strategies: (a) Mac alone running a pure-Python solver, (b) the Pi 3
running a C implementation in parallel across four AIPL worker actors
behind a least-loaded dispatcher, and (c) a Mac~+~Pi~3 split that
hands the lower-numbered first-column subtrees to the Mac and the
higher-numbered ones to the Pi 3.  The Pi 3 is a Raspberry Pi 3 B+
running 32-bit Embedded Xinu with MMU enabled, the periodic actor
garbage collector running, and four \texttt{CLASS\_Worker} actors
behind a \texttt{CLASS\_Dispatcher}.  Tasks are submitted over HTTP to
\texttt{/api/loadbal/nqueens}; results are polled via
\texttt{/api/loadbal/task?id=N}.
\end{abstract}

\section{System architecture}

The Pi 3 runtime under test (\texttt{xinu-rpi3}, branch
\texttt{arm-rpi3-port}) ships:
\begin{itemize}
  \item Embedded Xinu kernel with the ARMv7-A short-descriptor MMU
        enabled and an identity-mapped page table that distinguishes
        Normal-cacheable RAM from strongly-ordered Device MMIO.
  \item An AIPL actor system with a lock-free MPSC mailbox.
  \item A \texttt{CLASS\_Dispatcher} actor (priority 25) that routes
        \texttt{compute\_nq(n, first\_col)} messages round-robin to
        four \texttt{CLASS\_Worker} actors (priority 22).
  \item A \texttt{CLASS\_Collector} actor (priority 26) that
        periodically sweeps idle ephemeral actors and scans the
        in-memory task table for timed-out PENDING entries.
  \item HTTP server on port 8080 exposing the load-balancer control
        surface (\texttt{/api/loadbal/*}) and the GC actor
        (\texttt{/api/gc-actor/*}).
\end{itemize}

The N-Queens compute kernel on the Pi 3 is a $\mathrm{O}(N!)$ recursive
counter; on the Mac it is the identical algorithm in Python.  Splitting
by the first row's queen column is embarrassingly parallel --- each
\texttt{first\_col} subtree is independent and they are roughly
equal-cost.

\section{Methodology}

For each board size $N \in \{ __SIZES__ \}$ and each mode, the
benchmark runs the workload __REPEAT__ times back-to-back and reports
the \emph{median} wall-clock; means are sensitive to a one-off garbage
collection pause on either side.  Counts are sanity-checked to match
the known $N$-Queens solution numbers ($92$ for $N=8$, $352$ for
$N=9$, $724$ for $N=10$, $2680$ for $N=11$) and any mismatch is
flagged in the JSON.

\subsection{Modes}
\begin{description}
  \item[\texttt{mac}] Pure Python on the Mac.
  \item[\texttt{pi3}] All first columns submitted to Pi 3
        \texttt{/api/loadbal/nqueens}, polled until complete.
  \item[\texttt{split}] Mac handles \texttt{first\_col} $\in [0, N/2)$;
        Pi 3 handles $[N/2, N)$.  Both halves run concurrently from
        a Mac-side \texttt{ThreadPoolExecutor}.
\end{description}

\section{Results}

\begin{table}[h]
\centering
\begin{tabular}{cccccc}
\toprule
$N$ & solutions & Mac (ms) & Pi 3 (ms) & Split (ms) & Speedup (Mac/Split) \\
\midrule
__TABLE_ROWS__
\bottomrule
\end{tabular}
\caption{Median wall-clock times across __REPEAT__ repetitions per cell.
The Speedup column compares pure-Mac to the Mac+Pi3 split, so
$> 1.0$ means the distributed run was faster than Mac alone.}
\label{tab:results}
\end{table}

\begin{figure}[h]
\centering
\begin{tikzpicture}
\begin{axis}[
    width=12cm, height=7cm,
    ybar,
    bar width=8pt,
    ymode=log,
    log basis y={10},
    ylabel={Wall-clock (ms, log scale)},
    symbolic x coords={__X_COORDS__},
    xtick=data,
    enlarge x limits=0.15,
    legend pos=north west,
    nodes near coords,
    nodes near coords align={vertical},
    nodes near coords style={font=\tiny},
]
__PLOT_DATA__
\end{axis}
\end{tikzpicture}
\caption{Median wall-clock vs.\ board size $N$ (log-y).}
\label{fig:results}
\end{figure}

\section{Observations}

__OBSERVATIONS__

\section{Reproducing this report}

\begin{lstlisting}[language=bash]
# 1. Build + flash the Pi 3 kernel
cd ~/projects/xinu-raz/xinu/compile && make PLATFORM=arm-rpi3

# 2. Boot Pi 3 (SD swap or /kexec).  Then opt-in to the actors:
curl -X POST http://192.168.3.50:8080/api/loadbal/init
curl -X POST http://192.168.3.50:8080/api/gc-actor/init

# 3. Run the benchmark + render the report
cd ~/projects/xinu-raz/xinu/tools
./nqueens_bench.py --sizes __SIZES__ --pretty --out results.json
./build_report.py results.json --out report.tex --pdf report.pdf
\end{lstlisting}

\section{Raw benchmark data}

\begin{lstlisting}
__RAW_JSON__
\end{lstlisting}

\end{document}
"""


def cell_lookup(results, mode, n):
    for r in results:
        if r["mode"] == mode and r["n"] == n:
            if "error" in r:
                return None
            return r["median_ms"], r.get("count")
    return None


def render(data):
    results = data["results"]
    repeat = data["repeat"]
    sizes = sorted({r["n"] for r in results})

    rows = []
    plot_mac, plot_pi3, plot_split = [], [], []
    for n in sizes:
        mac = cell_lookup(results, "mac", n)
        pi3 = cell_lookup(results, "pi3", n)
        spl = cell_lookup(results, "split", n)
        sol = (mac or pi3 or spl or (None, None))[1]
        sol_s = str(sol) if sol is not None else "--"
        mac_s = str(mac[0]) if mac else "--"
        pi3_s = str(pi3[0]) if pi3 else "--"
        spl_s = str(spl[0]) if spl else "--"
        if mac and spl and spl[0] > 0:
            sp = f"{mac[0] / spl[0]:.2f}"
        else:
            sp = "--"
        rows.append(f"{n} & {sol_s} & {mac_s} & {pi3_s} & {spl_s} & {sp} \\\\")
        if mac:   plot_mac.append((n, mac[0]))
        if pi3:   plot_pi3.append((n, pi3[0]))
        if spl:   plot_split.append((n, spl[0]))

    def plot_series(name, data, color):
        coords = " ".join(f"({n},{ms})" for n, ms in data)
        return (f"\\addplot[fill={color}!40,draw={color}] coordinates {{{coords}}};\n"
                f"\\addlegendentry{{{name}}}")

    plot_data = "\n".join([
        plot_series("Mac (Python)", plot_mac, "blue"),
        plot_series("Pi 3 (4 workers)", plot_pi3, "red"),
        plot_series("Split (Mac + Pi 3)", plot_split, "green"),
    ])

    # Observation hints — auto-generate from the numbers.
    obs = []
    for n in sizes:
        mac = cell_lookup(results, "mac", n)
        pi3 = cell_lookup(results, "pi3", n)
        spl = cell_lookup(results, "split", n)
        if mac and pi3:
            ratio = pi3[0] / mac[0] if mac[0] > 0 else 0
            obs.append(f"For $N={n}$, the Pi 3 (4 workers, 1.4 GHz "
                       f"Cortex-A53 @ 32-bit) took {pi3[0]} ms versus "
                       f"the Mac's {mac[0]} ms ($\\approx {ratio:.1f}\\times$).")
        if mac and spl and spl[0] > 0 and mac[0] > 0:
            speedup = mac[0] / spl[0]
            if speedup > 1.05:
                obs.append(f"At $N={n}$, the Mac+Pi 3 split was "
                           f"{speedup:.2f}$\\times$ faster than Mac alone.")
            elif speedup < 0.95:
                obs.append(f"At $N={n}$, the Mac+Pi 3 split was actually "
                           f"slower ({speedup:.2f}$\\times$); for boards this "
                           f"small the HTTP round-trip + JSON polling "
                           f"overhead dominates the actual compute.")
    obs_tex = "\\begin{itemize}\n" + "\n".join(
        f"  \\item {o}" for o in obs) + "\n\\end{itemize}"

    import datetime
    today = datetime.date.today().isoformat()

    tex = TEX_TEMPLATE
    tex = tex.replace("__DATE__", today)
    tex = tex.replace("__SIZES__", ", ".join(str(s) for s in sizes))
    tex = tex.replace("__REPEAT__", str(repeat))
    tex = tex.replace("__TABLE_ROWS__", "\n".join(rows))
    tex = tex.replace("__X_COORDS__", ",".join(str(s) for s in sizes))
    tex = tex.replace("__PLOT_DATA__", plot_data)
    tex = tex.replace("__OBSERVATIONS__", obs_tex)
    tex = tex.replace("__RAW_JSON__", json.dumps(data, indent=2))
    return tex


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("results_json")
    ap.add_argument("--out", required=True, help="output .tex path")
    ap.add_argument("--pdf", help="run pdflatex to also produce this PDF")
    args = ap.parse_args()

    with open(args.results_json) as f:
        data = json.load(f)

    tex = render(data)
    with open(args.out, "w") as f:
        f.write(tex)
    print(f"wrote {args.out}", file=sys.stderr)

    if not args.pdf:
        return 0

    workdir = os.path.dirname(os.path.abspath(args.out)) or "."
    basename = os.path.basename(args.out).rsplit(".", 1)[0]
    # Run twice so the table+figure references settle.
    for i in range(2):
        r = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode",
             "-halt-on-error", basename + ".tex"],
            cwd=workdir, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout)
            sys.stderr.write(r.stderr)
            return 1
    out_pdf = os.path.join(workdir, basename + ".pdf")
    if os.path.abspath(out_pdf) != os.path.abspath(args.pdf):
        os.replace(out_pdf, args.pdf)
    print(f"wrote {args.pdf}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
